language: c
sudo: false
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-docker.sh
script: bash -ex .travis-docker.sh && bash -ex .docgen.sh
services:
  - docker
env:
 global:
   - secure: "BJobYIRLnVumkSlSwhTLLCFl0Li3IdpIoiuTkC39JJQzk6fyz/g86A56GXsENqwOCmWIARuZbc7F2UEMeV5Cd01P99DZdv9OC3fQUzgFEd7s+9AjYtFh91jKGEtsgC67gCxFayB9WkLiME9tkgDRNKvLRk1/9eXo776js8XG4FA="
   - PRE_INSTALL_HOOK="cd /home/opam/opam-repository && git pull origin master && opam update -u -y"
   - POST_INSTALL_HOOK="sh ./.travis-ci.sh"
   - PACKAGE="vchan"
   - DEPOPTS="mirage-xen xen-gnt xen-evtchn"
 matrix:
   - DISTRO=debian-stable OCAML_VERSION=4.02.3
   - DISTRO=debian-testing OCAML_VERSION=4.02.3
   - DISTRO=debian-unstable OCAML_VERSION=4.02.3
   - DISTRO=debian-testing OCAML_VERSION=4.03.0
   - DISTRO=debian-unstable OCAML_VERSION=4.03.0
   - DISTRO=ubuntu-16.04 OCAML_VERSION=4.02.3
   - DISTRO=ubuntu-16.04 OCAML_VERSION=4.03.0
   - DISTRO=centos-7 OCAML_VERSION=4.02.3
   - DISTRO=fedora-24 OCAML_VERSION=4.02.3
